### ISSUE TITLE
Device names keep resetting

### ISSUE THREAD

**Issue by stevesmith69** [mysensors/Vera#13]
![screen shot 2015-06-16 at 00 05 01](https://cloud.githubusercontent.com/assets/12543259/8172748/a6cb2346-13bb-11e5-8ad9-30751568287f.jpg)

After uploading the latest release of the L_Arduino.lua file, the device names keep reverting back to the version number and node number e.g.  1.4.1 (7).  I'm using UI7 on a Vera Edge.  If I rename the device within Vera, and the power cycle the node the name reverts back to 1.4.1 (7).

**Comment by henrikekblad** [comment]
That is not the correct behaviour. It should only update name during inclusion mode (if node sends out name in presentation). I will look at this during the coming days. In the meantime you can revert back to the previous version.

https://github.com/mysensors/Vera/tree/c02e16c020e4822c13aaadbd87baa479b3a94c12

**Comment by henrikekblad** [comment]
Done some more testing but cannot fully reproduce the problem you're seeing. 

The device-naming feature is supposed to work like this;

A nodes attached sensor now have the option to send in a device name/description. This name is picket up during inclusion mode and set when device is created the first time.
If a sensor already has been added to Vera you can still update the sensor (from the node) name but you have to start inclusion mode and restart the node. So name should only be overwritten when enabling inclusion mode AND reset node.

When reading your description I got the impression the name was being set every time you reset the node? Or did you have inclusion mode enabled when you saw this?

There still is a bug where older sensors is sending in the library version (as name) for all attached sensors. I will fix this problem in the vera plugin (basically ignoring names starting with "1.").

**Comment by henrikekblad** [comment]
Fixed
