### ISSUE TITLE
PressureSensor speaks French

### ISSUE THREAD

**Issue by bliekp** [mysensors/Vera#51]
I have built the PressureSensor and it all works well, except it prints out French text on my Vera...

I have used the files from: http://www.mysensors.org/controller/vera
(not the latest GitHub versions though...)
And uploaded them to Vera.

On the Serial Monitor the readings are:

Temperature = 19.80 *C
Pressure = 999.30 hPa
Forecast = unknown

On the Vera I get:

Il faudrait une police plus petite 999

Nowhere in my settings in the Vera it says French language is preferred.... Weird!

**Comment by bliekp** [comment]
Found a solution here: http://forum.mysensors.org/topic/2613/barometer-pressure-sensor-display-incorrectly-in-ui7/6

**Comment by gervaso** [comment]
I'll create a pull request with the correct json file.
